name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Buildozer Action
        uses: ArtemSerebrennikov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.10
        id: buildozer

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
